WebProject2/Models/UserLockdownViewModel.cs
namespace WebProject2.Models
{
    public class UserLockdownViewModel
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string Email { get; set; }
        public bool isLockDown { get; set; }
    }
}

WebProject2/Controllers/UserLockdownController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebProject2.Enum;
using WebProject2.Models;

namespace WebProject2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserLockdownController : Controller
    {
        private readonly UserManager<Client> _userManager;
        public UserLockdownController(UserManager<Client> userManager)
        {
            _userManager = userManager;  
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userLockdownViewModel = new List<UserLockdownViewModel>();
            foreach (Client u in users)
            {
                var thisViewModel = new UserLockdownViewModel();
                thisViewModel.UserId = u.Id;
                thisViewModel.FirstName = u.FirstName;
                thisViewModel.LastName = u.LastName;
                thisViewModel.Email = u.Email;
                if (u.LockoutEnd == null){
                    thisViewModel.isLockDown = false;
                }
                userLockdownViewModel.Add(thisViewModel);
            }

            return  View(userLockdownViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.UserId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            ViewBag.UserName = user.UserName;

            var model = new ManageUserLockdownViewModel();
            model.Lockdown = "Looked down";
            if (user.LockoutEnd != null){ model.Selected = true; }
            else { model.Selected = false; }
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Manage(ManageUserLockdownViewModel model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }

            var result = await _userManager.SetLockoutEndDateAsync(user,DateTime.Now);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove lockdown from user");
                return View(model);
            }

            if (model.Selected == true)
            {
                var result2 = await _userManager.SetLockoutEndDateAsync(user,DateTime.Now.AddYears(100));
                if (!result2.Succeeded)
                {
                    ModelState.AddModelError("", "Cannot apply lockdown to user");
                }
            }

            return RedirectToAction("Index");
        }




    }
}

WebProject2/Views/UserLockdown/Index.cshtml
@using WebProject2.Models
@model List<WebProject2.Models.UserLockdownViewModel>
@{
    ViewData["Title"] = "User Lockdown Manager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewData["Title"]</h1>
<table class=" table table-striped">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Locked down?</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
                <tr>
                    <td>@user.FirstName</td>
                    <td>@user.LastName</td>
                    <td>@user.Email</td>
                    <td>@user.isLockDown</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="UserLockdown" 
                        asp-action="Manage" asp-route-userId="@user.UserId">Manage</a>
                    </td>
                </tr>
        }
    </tbody>

</table>

WebProject2/Views/UserLockdown/Manage.cshtml
@model WebProject2.Models.ManageUserLockdownViewModel
@{
    ViewData["Title"] = "Manage Roles for Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Manage User Lock</h2>
            Add/Remove Lock down for the User / @ViewBag.UserName 
        </div>


        <div class="card-body">       
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model.Lockdown">
                    <input asp-for="@Model.Selected" class="form-check-input">
                    <label class="form-check-label" asp-for="@Model.Selected">@Model.Lockdown</label>
                </div>
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>


        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
            <a asp-action="Index" class="btn btn-primary" style="width:auto">Cancel</a>
        </div>


    </div>



</form>

WebProject2/Views/UserLockdown/NotFound.cshtml

  <body>
    <div class="d-flex align-items-center justify-content-center vh-100 bg-primary">
        <h1 class="display-1 fw-bold text-white">User not Found</h1>
    </div>
  </body>