WebProject2/Models/ShopProduct.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebProject2.Models
{
    public class ShopProduct
    {
        public int Id { get; set; }
        public string? ImageUrl { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? Description { get; set; }

        public string? Category { get; set; }
        /*[EnumDataType(typeof(ProductCategory))]
        public ProductCategory Category { get; set; }*/
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Price { get; set; }
        [DataType(DataType.Date)]
        public DateTime AuctionStartDate { get; set; }
        [DataType(DataType.Date)]
        public DateTime AuctionEndDate { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public string? SellerUserId { get; set; }

        // Define a list of available categories 
        
       /* public enum ProductCategory
        {
           Laptops,
           Smartphones,
           Cameras,
           iPad,
           Headsets

        }*/
        [NotMapped]
        public int RemainingDays
        {
            get
            {
                TimeSpan remainingTime = AuctionEndDate - DateTime.Today;
                return remainingTime.Days;
            }
        }
    }
}

WebProject2/Controllers/ShopProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WebProject2.Data;
using WebProject2.Models;
using WebProject2.ViewModels;

namespace WebProject2.Controllers
{
    public class ShopProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShopProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ShopProducts
        public async Task<IActionResult> Index(string shopProductCategory, string search)
        {
            IQueryable<string> categoryQuery = from c in _context.ShopProduct
                                               orderby c.Category
                                               select c.Category;

            var shopProducts = from p in _context.ShopProduct
                           select p;
            if (!string.IsNullOrEmpty(search))
            {
                shopProducts = shopProducts.Where(s => s.Name!.Contains(search));
            }

            if (!string.IsNullOrEmpty(shopProductCategory))
            {
                shopProducts = shopProducts.Where(p => p.Category == shopProductCategory);
            }

            var shopProductCategoryVM = new ShopProductCategoryViewModel
            {
                Categories = new SelectList(await categoryQuery.Distinct().ToListAsync()),
                ShopProducts = await shopProducts.ToListAsync()
            };

            return View(shopProductCategoryVM);
             
        }

        // GET: ShopProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // get the current user ID and save to ViewBag
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.UserId = userId;

            if (id == null || _context.ShopProduct == null)
            {
                return NotFound();
            }

            var shopProduct = await _context.ShopProduct
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shopProduct == null)
            {
                return NotFound();
            }

            return View(shopProduct);
        }

        // GET: ShopProducts/Create
        public IActionResult Create()
        {
            /*ViewBag.Categories = new SelectList(Enum.GetValues(typeof(ProductCategory)));*/
            return View();
        }

        // POST: ShopProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImageUrl,Name,Description,Category,Price,AuctionStartDate,AuctionEndDate,Quantity,SellerUserId")] ShopProduct shopProduct)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shopProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           /* ViewBag.Categories = new SelectList(Enum.GetValues(typeof(ProductCategory)));*/
            return View(shopProduct);
        }

        // GET: ShopProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ShopProduct == null)
            {
                return NotFound();
            }

            var shopProduct = await _context.ShopProduct.FindAsync(id);
            if (shopProduct == null)
            {
                return NotFound();
            }
            return View(shopProduct);
        }

        // POST: ShopProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageUrl,Name,Description,Category,Price,AuctionStartDate,AuctionEndDate,Quantity,SellerUserId")] ShopProduct shopProduct)
        {
            if (id != shopProduct.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shopProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopProductExists(shopProduct.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shopProduct);
        }

        // GET: ShopProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ShopProduct == null)
            {
                return NotFound();
            }

            var shopProduct = await _context.ShopProduct
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shopProduct == null)
            {
                return NotFound();
            }

            return View(shopProduct);
        }

        // POST: ShopProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ShopProduct == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ShopProduct'  is null.");
            }
            var shopProduct = await _context.ShopProduct.FindAsync(id);
            if (shopProduct != null)
            {
                _context.ShopProduct.Remove(shopProduct);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopProductExists(int id)
        {
          return (_context.ShopProduct?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebProject2/Views/ShopProducts/Create.cshtml

@model WebProject2.Models.ShopProduct

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ShopProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            @*<div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                @Html.DropDownListFor(model => model.Category, new SelectList(Enum.GetValues(typeof(ProductCategory))), "-- Select a category --", new { @class = "form-control" })
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionStartDate" class="control-label"></label>
                <input asp-for="AuctionStartDate" class="form-control" />
                <span asp-validation-for="AuctionStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionEndDate" class="control-label"></label>
                <input asp-for="AuctionEndDate" class="form-control" />
                <span asp-validation-for="AuctionEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SellerUserId" class="control-label"></label>
                <input asp-for="SellerUserId" class="form-control" />
                <span asp-validation-for="SellerUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebProject2/Views/ShopProducts/Delete.cshtml
@model WebProject2.Models.ShopProduct

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShopProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuctionStartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuctionStartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuctionEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuctionEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SellerUserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SellerUserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebProject2/Views/ShopProducts/Details.cshtml
@model WebProject2.Models.ShopProduct

@{
    ViewData["Title"] = "Details";
}

<h1>Product Page</h1>

<div>
    
    <hr />
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid" src="@Model.ImageUrl" alt="@Model.Name" />
        </div>
        <div class="col-md-6">
             <h2 class="h2-responsive font-weight-bold">@Model.Name</h2>
             <p class="lead">@Model.Description</p>
             <p><strong>Category:</strong> @Model.Category</p>
            <p><strong>Price:</strong> $@Model.Price</p>
            <p><strong>Auction Start Date:</strong> @Model.AuctionStartDate.ToShortDateString()</p>
            <p><strong>Auction End Date:</strong> @Model.AuctionEndDate.ToShortDateString()</p>
         <div class="form-group">
            <label for="quantity">Quantity:</label>
            <input type="number" class="form-control" id="quantity" min="1" max="@Model.Quantity" value="1">
        </div>
            @if (ViewBag.UserId != null && ViewBag.UserId != Convert.ToString(Model.SellerUserId))
            {
                <!-- <button class="btn btn-primary">Bid</button> -->
                <button class="btn btn-primary" id="add-to-cart">Add to Cart</button>
            }
            else if (ViewBag.UserId == null)
            {
                <button class="btn btn-primary">Login to Bid</button>
            }
         
         </div>
    </div>

</div>
<div>
    @if (ViewBag.UserId == Model.SellerUserId)
    {
        <p>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </p>
    }
    else
    {
        <a asp-action="Index">Back to List</a>
    }

</div>
@*<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@

WebProject2/Views/ShopProducts/Edit.cshtml
@model WebProject2.Models.ShopProduct

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ShopProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionStartDate" class="control-label"></label>
                <input asp-for="AuctionStartDate" class="form-control" />
                <span asp-validation-for="AuctionStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionEndDate" class="control-label"></label>
                <input asp-for="AuctionEndDate" class="form-control" />
                <span asp-validation-for="AuctionEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SellerUserId" class="control-label"></label>
                <input asp-for="SellerUserId" class="form-control" />
                <span asp-validation-for="SellerUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebProject2/Views/ShopProducts/Index.cshtml
@model WebProject2.ViewModels.ShopProductCategoryViewModel

@{
    ViewData["Title"] = "Index";
}

<!-- Search Bar below -->
<div class="container mt-3">
    <form class="form-inline" asp-asp-controller="ShopProducts" asp-action="Index" method="get">
        <div class="input-group">
            
                <select asp-for = "ShopProductCategory" asp-items ="Model.Categories">
                    <option value="">All Categories</option>
                </select>
                
                    <input type="text" class="form-control" placeholder="Search..." name="search">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            Search
                        </button>
                        <button class="btn btn-primary" type="submit" asp-action="Create">
                            Create
                        </button>
                
                    </div>
           
        </div>
    </form>
</div>

<div class="container py-4">
    <div class="row">
        @foreach (var item in Model.ShopProducts)
        {
            <div class="col-md-12 col-lg-4 mb-3 mb-lg-0" >
                <div class="card px-4 mb-4">

                    <a asp-action="Details" asp-controller="ShopProducts" asp-route-id="@item.Id">
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)"
                         class="card-img-top" />
                    </a>

                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="small"><class="text-muted">@Html.DisplayFor(modelItem => item.Category)</p>  <!-- Item Type/ Category -->
                        </div>

                        <div class="d-flex justify-content-between mb-3">
                            <h5 class="mb-0">@Html.DisplayFor(modelItem => item.Name)</h5>  <!-- Item Name -->
                            <h5 class="text-dark mb-0">$@Html.DisplayFor(modelItem => item.Price)</h5> <!-- Item Price -->
                        </div>

                        <div class="d-flex justify-content-between mb-2">
                            <p class="text-muted mb-0">
                                Ending Bid in: <span class="fw-bold">
                                    @Html.DisplayFor(modelItem => item.RemainingDays)
                                </span> Days!
                            </p> <!-- Item bid end date-->
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
